name: restServer
description: A simple restful server written in dart and appwrite
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0
  shelf_router: ^0.7.4
  dart_appwrite: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.0
